- name: db install
  connection: local
  hosts: localhost
  sudo: yes

  tasks:
  - name: apt-get update
    apt: update_cache=yes
    register: result
    until: result|success
    retries: 10

  - name: install mysql-server
    apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
    with_items:
      - mysql-server
      - python-mysqldb

  - name: Update bind-address
    lineinfile: dest=/etc/mysql/my.cnf regexp='^bind-address*' line='#bind-address'

  - name: restart mysql
    service: name=mysql state=restarted

  - name: create database
    mysql_db: name={{ db_name }} state=present

  - name: create nova user
    mysql_user: name={{ db_user }} host={{ item }} password={{ db_password }} priv={{ db_name }}.*:ALL state=present
    with_items:
      - localhost
      - "%"


