heat_template_version: 2017-02-24

description: >
  My autoscaling test template using event alarm.
  By executing openstack image set, scaling up servers.

parameters:
  flavor:
    type: string
    description: Flavor for the instances to be created
    default: none
    constraints:
      - custom_constraint: nova.flavor
        description: Must be a flavor known to Nova

  image:
    type: string
    description: >
      Name or ID of the image to use for the instances.
    default: none
    constraints:
      - custom_constraint: glance.image
        description: Must identify an image known to Glance

  network:
    type: string
    description: The network for the VM
    default: private

resources:
  asg:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 1
      max_size: 3
      resource:
        type: server.yaml
        properties:
          image: {get_param: image}
          flavor: {get_param: flavor}
          network: {get_param: network}

  scale_up_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 60
      scaling_adjustment: 1

  scale_down_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 60
      scaling_adjustment: '-1'

  image_update_alarm:
    type: OS::Aodh::EventAlarm
    properties:
      repeat_actions: false
      event_type: image.update
      query:
        - field: traits.resource_id
          value: {get_param: image}
          op: eq
          type: string
      alarm_actions:
        - {get_attr: [scale_up_policy, alarm_url]}

outputs:
  scale_up_url:
    description: >
      This URL is the webhook to scale up the group.  You can invoke
      the scale-up operation by doing an HTTP POST to this URL; no
      body nor extra headers are needed.
    value: {get_attr: [scale_up_policy, alarm_url]}
  scale_dn_url:
    description: >
      This URL is the webhook to scale down the group.  You can invoke
      the scale-down operation by doing an HTTP POST to this URL; no
      body nor extra headers are needed.
    value: {get_attr: [scale_down_policy, alarm_url]}
